### ISSUE TITLE
Show module type definitions

### ISSUE THREAD

**Issue by mankinskin** [regexident/cargo-modules#64] opened 2020-10-08 20:33 UTC
Hello, what do you guys think about adding a flag for showing the types defined in a module? This might seem out of scope for this project, but it is sort of an extension of the module tree in a syntactic meaning, because of the way you reference types in other modules.

This could be extended for functions aswell, maybe even methods or trait implementations

I imagine this to look something like this:
```rust
% cargo modules --enable-edition-2018 tree --types
server : crate
 ├── websocket : private
 ├── message_stream : orphan
 │    ├── struct MessageStream
 │    └── impl futures::Stream for MessageStream
 └── websocket : private
     ├── struct WebSocket
     │    ├── fn new(host: &str) -> Self
     │    └── fn close(&self)
     └── enum Msg
```

**Comment by regexident** [comment] 2020-10-08 21:37
Hi @mankinskin, that's certainly something I would love to have!

I'm currently looking into https://github.com/regexident/cargo-modules/issues/63, with should finally allow me to tackle a few of the more elaborate open issues (by extending cargo-module's current syntactic parser with semantics from a type resolver).

(Closing this as it's essentially a duplicate of https://github.com/regexident/cargo-modules/issues/48)

**Closed by regexident** 2020-10-08 21:37 UTC
